1-1: BookStore.cpp main-1-1.cpp
	g++ BookStore.cpp main-1-1.cpp -o 1-1
	./1-1


2-1: BookStore.cpp Dymocks.cpp main-2-1.cpp
	g++ BookStore.cpp Dymocks.cpp main-2-1.cpp -o 2-1
	./2-1

2-2: BookStore.cpp Dymocks.cpp BarnesNoble.cpp main-2-2.cpp
	g++ BookStore.cpp Dymocks.cpp BarnesNoble.cpp main-2-2.cpp -o 2-2
	./2-2

3-1: BookStore.cpp Dymocks.cpp BarnesNoble.cpp StoreChain.cpp  main-3-1.cpp
	g++ BookStore.cpp Dymocks.cpp BarnesNoble.cpp StoreChain.cpp main-3-1.cpp -o 3-1
	./3-1